# Generated by Django 5.0.6 on 2024-06-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_odds_product_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='analysis',
            field=models.TextField(default='No analysis available yet.', max_length=40),
        ),
    ]
